blog/urls.py
from rest_framework import routers

from .api import PostViewSet


router = routers.DefaultRouter()
router.register('/posts', PostViewSet)


urlpatterns = router.urls

example/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('api', include('blog.urls'))
]

blog/models.py
from django.db import models


class Post(models.Model):
    text = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']

    text = forms.CharField(
        min_length=10,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

blog/views.py
from django.views import View
from django.views.generic import ListView, CreateView
from .models import Post
from .forms import PostForm


class PostListView(ListView):
    template_name = 'index.html'
    model = Post
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-created_at')
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = PostForm()
        return context


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    success_url = '/'


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return PostListView.as_view()(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return PostCreateView.as_view()(request, *args, **kwargs)

blog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}"/>

    <title>Hello, world!</title>
  </head>
  <body>
    <div class="content">
      {% block content %}
      {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="{% static 'main.js' %}"></script>
  </body>
</html>

blog/templates/index.html
{% extends "base.html" %}
{% block content %}
{% include "nav.html" %}
{% verbatim %}
<main role="main" class="container">
  <div class="form-group">
    <label for="id_text">Text</label>
    <input type="text" name="text" minlength="10" required="required" id="id_text" class="form-control">
  </div>
  <button class="btn btn-primary" @click="addPost">Submit</button>

  <div class="post" v-for="post in posts">
    <post :post="post"></post>
  </div>
</main><!-- /.container -->
{% endverbatim %}
{% endblock content %}

blog/templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

blog/templates/post.html
<div class="post">
  <p>{{ post.text }}</p>
  <p>{{ post.created_at }}</p>
</div>

blog/templates/post_form.html
<form method="POST">
  {% csrf_token %}

  {{ form.non_field_errors }}

  <div class="form-group">
    {{ form.text.errors }}
    <label for="{{ form.text.id_for_label }}">Text</label>
    {{ form.text }}
  </div>

  <button class="btn btn-primary" type="submt">Submit</button>
</form>